version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=secret_token
    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/product-service
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/order-service
      - PRODUCT_SERVICE_URL=http://product-service:5002/api/products
    depends_on:
      - mongodb
      - product-service

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - product-service
      - order-service
